//document.addEventListener("DOMContentLoaded", 
 var num1;
var num3;
var num2;
var picu;
var num4;
var num5;
var num6;
var num7;
var num8;
var num9;
var num10;
var num11;
var num12;
var num13;
var num14;
var num15;
var num16;
var num17;
var num18;
var num19;
var num20;
var num21;
var num22;
var num23;
var num24;
var num25;
var num26;
var num27;
var num28;
var num29;
var num30;
var num31;
var num32;
var num33;
var num34;
var num35;
var num36;
var num37;
var num38;
var num39;
var num40;
var num41;
var num42;
var num43;
var num44;
var num45;
var num46;
var num47;
var num48;
var num49;
var num50;
var num51;
var num52;
var num53;
var num54;
var num55;
var num56;
var num57;
var num58;
var num59;
var num60;
var num61;
var num62;
var num63;
var num64;
var num65;
var num66;
var num67;
var num68;
var num69;
var num70;
var num71;
var num72;
var num73;
var num74;
var num75;
var num76;
var num77;
var num78;
var num79;
var num80;
var num81;
var num82;
var num83;
var num84;
var num85;
var num86;
var num87;
var num88;
var num89;
var num90;
var num91;
var num92;
var num93;
var num94;
var num95;
var num96;
var num97;
var num98;
var num99;
var num100;
var num101;
var num102;
var num103;
var num104;
var num105;
var num106;
var num107;
var num108;
var num109;
var num110;
var num111;
var num112;
var num113;
var num114;
var num115;
var num116;
var num117;
var num118;
var num119;
var num120;
var num121;
var num122;
var num123;
var num124;
var num125;
var num126;
var num127;
var num128;
var num129;
var num130;
var num131;
var num132;
var num133;
var num134;
var num135;
    function multiplyBy() {
    num1 = document.getElementById('<%=ammounting.ClientID%>').value;
    docume;nt.getElementById('<%=ammounting1.ClientID%>').innerHTML = num1;
    document.getElementById('<%=ammounting2.ClientID%>').innerHTML = num1;
    document.getElementById('<%=ammounting3.ClientID%>').innerHTML = num1;
    document.getElementById('<%=ammounting4.ClientID%>').innerHTML = num1;
    document.getElementById('<%=ammounting5.ClientID%>').innerHTML = num1;
    document.getElementById('<%=ammounting6.ClientID%>').innerHTML = num1;
    document.getElementById('<%=ammounting7.ClientID%>').innerHTML = num1;
     num3 = document.getElementById('<%=Label3.ClientID%>').innerHTML;
     num2 = document.getElementById('<%=Label2.ClientID%>').innerHTML;
     picu = parseFloat((1 / 100).toFixed(2));
     num4 = document.getElementById('<%=Label00.ClientID%>').innerHTML;
     num5 = document.getElementById('<%=Label4.ClientID%>').innerHTML;
     num6 = document.getElementById('<%=Label5.ClientID%>').innerHTML;
     num7 = document.getElementById('<%=Label7.ClientID%>').innerHTML;
     num8 = document.getElementById('<%=Label8.ClientID%>').innerHTML;
     num9 = document.getElementById('<%=Label9.ClientID%>').innerHTML;
     num10 = document.getElementById('<%=Label50.ClientID%>').innerHTML;
     num11 = document.getElementById('<%=Label51.ClientID%>').innerHTML;
     num12 = document.getElementById('<%=Label52.ClientID%>').innerHTML;
     num13 = document.getElementById('<%=Label53.ClientID%>').innerHTML;
     num14 = document.getElementById('<%=Label54.ClientID%>').innerHTML;
     num15 = document.getElementById('<%=Label55.ClientID%>').innerHTML;
     num16 = document.getElementById('<%=Label61.ClientID%>').innerHTML;
     num17 = document.getElementById('<%=Label65.ClientID%>').innerHTML;
     num18 = document.getElementById('<%=Label66.ClientID%>').innerHTML;
     num19 = document.getElementById('<%=Label67.ClientID%>').innerHTML;
     num20 = document.getElementById('<%=Label68.ClientID%>').innerHTML;
     num21 = document.getElementById('<%=Label69.ClientID%>').innerHTML;
     num22 = document.getElementById('<%=Label70.ClientID%>').innerHTML;
     num23 = document.getElementById('<%=Label72.ClientID%>').innerHTML;
     num24 = document.getElementById('<%=Label74.ClientID%>').innerHTML;
     num25 = document.getElementById('<%=Label76.ClientID%>').innerHTML;
     num26 = document.getElementById('<%=Label73.ClientID%>').innerHTML;
     num27 = document.getElementById('<%=Label75.ClientID%>').innerHTML;
     num28 = document.getElementById('<%=Label71.ClientID%>').innerHTML;
     num29 = document.getElementById('<%=Label77.ClientID%>').innerHTML;
     num30 = document.getElementById('<%=Label78.ClientID%>').innerHTML;
     num31 = document.getElementById('<%=Label79.ClientID%>').innerHTML;
     num32 = document.getElementById('<%=Label80.ClientID%>').innerHTML;
     num33 = document.getElementById('<%=Label81.ClientID%>').innerHTML;
     num34 = document.getElementById('<%=Label82.ClientID%>').innerHTML;
     num35 = document.getElementById('<%=Label83.ClientID%>').innerHTML;
     num36 = document.getElementById('<%=Label10.ClientID%>').innerHTML;
     num37 = document.getElementById('<%=Label11.ClientID%>').innerHTML;
     num38 = document.getElementById('<%=Label12.ClientID%>').innerHTML;
     num39 = document.getElementById('<%=Label13.ClientID%>').innerHTML;
     num40 = document.getElementById('<%=Label14.ClientID%>').innerHTML;
     num41 = document.getElementById('<%=Label15.ClientID%>').innerHTML;
     num42 = document.getElementById('<%=Label16.ClientID%>').innerHTML;
     num43 = document.getElementById('<%=Label17.ClientID%>').innerHTML;
     num44 = document.getElementById('<%=Label18.ClientID%>').innerHTML;
     num45 = document.getElementById('<%=Label19.ClientID%>').innerHTML;
     num46 = document.getElementById('<%=Label20.ClientID%>').innerHTML;
     num47 = document.getElementById('<%=Label21.ClientID%>').innerHTML;
     num48 = document.getElementById('<%=Label22.ClientID%>').innerHTML;
     num49 = document.getElementById('<%=Label23.ClientID%>').innerHTML;
     num50 = document.getElementById('<%=Label24.ClientID%>').innerHTML;
     num51 = document.getElementById('<%=Label25.ClientID%>').innerHTML;
     num52 = document.getElementById('<%=Label26.ClientID%>').innerHTML;
     num53 = document.getElementById('<%=Label40.ClientID%>').innerHTML;
     num54 = document.getElementById('<%=Label62.ClientID%>').innerHTML;
     num55 = document.getElementById('<%=Label32.ClientID%>').innerHTML;
     num56 = document.getElementById('<%=Label33.ClientID%>').innerHTML;
     num57 = document.getElementById('<%=Label41.ClientID%>').innerHTML;
     num58 = document.getElementById('<%=Label31.ClientID%>').innerHTML;
     num59 = document.getElementById('<%=Label30.ClientID%>').innerHTML;
     num60 = document.getElementById('<%=Label27.ClientID%>').innerHTML;
     num61 = document.getElementById('<%=Label28.ClientID%>').innerHTML;
     num62 = document.getElementById('<%=Label29.ClientID%>').innerHTML;
     num63 = document.getElementById('<%=Label34.ClientID%>').innerHTML;
     num64 = document.getElementById('<%=Label35.ClientID%>').innerHTML;
     num65 = document.getElementById('<%=Label36.ClientID%>').innerHTML;
     num66 = document.getElementById('<%=Label37.ClientID%>').innerHTML;
     num67 = document.getElementById('<%=Label84.ClientID%>').innerHTML;
     num68 = document.getElementById('<%=Label85.ClientID%>').innerHTML;
     num69 = document.getElementById('<%=Label42.ClientID%>').innerHTML;
     num70 = document.getElementById('<%=Label43.ClientID%>').innerHTML;
     num71 = document.getElementById('<%=Label44.ClientID%>').innerHTML;
     num72 = document.getElementById('<%=Label96.ClientID%>').innerHTML;
     num73 = document.getElementById('<%=Label99.ClientID%>').innerHTML;
     num74 = document.getElementById('<%=Label105.ClientID%>').innerHTML;
     num75 = document.getElementById('<%=Label107.ClientID%>').innerHTML;
     num76 = document.getElementById('<%=Label135.ClientID%>').innerHTML;
     num77 = document.getElementById('<%=Label139.ClientID%>').innerHTML;
     num78 = document.getElementById('<%=Label117.ClientID%>').innerHTML;
     num79 = document.getElementById('<%=Label118.ClientID%>').innerHTML;
     num80 = document.getElementById('<%=Label120.ClientID%>').innerHTML;
     num81 = document.getElementById('<%=Label121.ClientID%>').innerHTML;
     num82 = document.getElementById('<%=Label122.ClientID%>').innerHTML;
     num83 = document.getElementById('<%=Label123.ClientID%>').innerHTML;
     num84 = document.getElementById('<%=Label98.ClientID%>').innerHTML;
     num85 = document.getElementById('<%=Label45.ClientID%>').innerHTML;
     num86 = document.getElementById('<%=Label136.ClientID%>').innerHTML;
     num87 = document.getElementById('<%=Label140.ClientID%>').innerHTML;
     num88 = document.getElementById('<%=Label126.ClientID%>').innerHTML;
     num89 = document.getElementById('<%=Label127.ClientID%>').innerHTML;
     num90 = document.getElementById('<%=Label128.ClientID%>').innerHTML;
     num91 = document.getElementById('<%=Label137.ClientID%>').innerHTML;
     num92 = document.getElementById('<%=Label138.ClientID%>').innerHTML;
     num93 = document.getElementById('<%=Label141.ClientID%>').innerHTML;
     num94 = document.getElementById('<%=Label86.ClientID%>').innerHTML;
     num95 = document.getElementById('<%=Label87.ClientID%>').innerHTML;
     num96 = document.getElementById('<%=Label88.ClientID%>').innerHTML;
     num97 = document.getElementById('<%=Label89.ClientID%>').innerHTML;
     num98 = document.getElementById('<%=Label90.ClientID%>').innerHTML;
     num99 = document.getElementById('<%=Label133.ClientID%>').innerHTML;
     num100 = document.getElementById('<%=Label91.ClientID%>').innerHTML;
     num101 = document.getElementById('<%=Label112.ClientID%>').innerHTML;
     num102 = document.getElementById('<%=Label92.ClientID%>').innerHTML;
     num103 = document.getElementById('<%=Label113.ClientID%>').innerHTML;
     num104 = document.getElementById('<%=Label93.ClientID%>').innerHTML;
     num105 = document.getElementById('<%=Label94.ClientID%>').innerHTML;
     num106 = document.getElementById('<%=Label100.ClientID%>').innerHTML;
     num107 = document.getElementById('<%=Label114.ClientID%>').innerHTML;
     num108 = document.getElementById('<%=Label95.ClientID%>').innerHTML;
     num109 = document.getElementById('<%=Label106.ClientID%>').innerHTML;
     num110 = document.getElementById('<%=Label97.ClientID%>').innerHTML;
     num111 = document.getElementById('<%=Label101.ClientID%>').innerHTML;
     num112 = document.getElementById('<%=Label102.ClientID%>').innerHTML;
     num113 = document.getElementById('<%=Label104.ClientID%>').innerHTML;
     num114 = document.getElementById('<%=Label103.ClientID%>').innerHTML;
     num115 = document.getElementById('<%=Label119.ClientID%>').innerHTML;
     num116 = document.getElementById('<%=Label115.ClientID%>').innerHTML;
     num117 = document.getElementById('<%=Label116.ClientID%>').innerHTML;
     num118 = document.getElementById('<%=Label124.ClientID%>').innerHTML;
     num119 = document.getElementById('<%=Label125.ClientID%>').innerHTML;
     num120 = document.getElementById('<%=Label129.ClientID%>').innerHTML;
     num121 = document.getElementById('<%=Label134.ClientID%>').innerHTML;
     num122 = document.getElementById('<%=Label130.ClientID%>').innerHTML;
     num123 = document.getElementById('<%=Label131.ClientID%>').innerHTML;
     num124 = document.getElementById('<%=Label132.ClientID%>').innerHTML;
     num125 = document.getElementById('<%=Label38.ClientID%>').innerHTML;
     num126 = document.getElementById('<%=Label39.ClientID%>').innerHTML;
     num127 = document.getElementById('<%=Label58.ClientID%>').innerHTML;
     num128 = document.getElementById('<%=Label59.ClientID%>').innerHTML;
     num129 = document.getElementById('<%=Label56.ClientID%>').innerHTML;
     num130 = document.getElementById('<%=Label57.ClientID%>').innerHTML;
     num131 = document.getElementById('<%=Label108.ClientID%>').innerHTML;
     num132 = document.getElementById('<%=Label109.ClientID%>').innerHTML;
     num133 = document.getElementById('<%=Label110.ClientID%>').innerHTML;
     num134 = document.getElementById('<%=Label111.ClientID%>').innerHTML;
     num135 = document.getElementById('<%=Label64.ClientID%>').innerHTML;
    document.getElementById('<%=result.ClientID%>').innerHTML = parseFloat((num1 * num2 * picu).toFixed(2));
    document.getElementById('<%=result1.ClientID%>').innerHTML = parseFloat((num1 * num3 * picu).toFixed(2));
    document.getElementById('<%=result2.ClientID%>').innerHTML = parseFloat((num1 * num4 * picu).toFixed(2));
    document.getElementById('<%=result3.ClientID%>').innerHTML = parseFloat((num1 * num5 * picu).toFixed(2));
    document.getElementById('<%=result4.ClientID%>').innerHTML = parseFloat((num1 * num6 * picu).toFixed(2));
    document.getElementById('<%=result6.ClientID%>').innerHTML = parseFloat((num1 * num8 * picu).toFixed(2));
    document.getElementById('<%=result5.ClientID%>').innerHTML = parseFloat((num1 * num7 * picu).toFixed(2));
    document.getElementById('<%=result7.ClientID%>').innerHTML = parseFloat((num1 * num9 * picu).toFixed(2));
    document.getElementById('<%=result8.ClientID%>').innerHTML = parseFloat((num1 * num10 * picu).toFixed(2));
    document.getElementById('<%=result9.ClientID%>').innerHTML = parseFloat((num1 * num11 * picu).toFixed(2));
    document.getElementById('<%=result10.ClientID%>').innerHTML = parseFloat((num1 * num12 * picu).toFixed(2));
    document.getElementById('<%=result11.ClientID%>').innerHTML = parseFloat((num1 * num13 * picu).toFixed(2));
    document.getElementById('<%=result12.ClientID%>').innerHTML = parseFloat((num1 * num14 * picu).toFixed(2));
    document.getElementById('<%=result13.ClientID%>').innerHTML = parseFloat((num1 * num15 * picu).toFixed(2));
    document.getElementById('<%=result14.ClientID%>').innerHTML = parseFloat((num1 * num16 * picu).toFixed(2));
    document.getElementById('<%=result15.ClientID%>').innerHTML = parseFloat((num1 * num17 * picu).toFixed(2));
    document.getElementById('<%=result16.ClientID%>').innerHTML = parseFloat((num1 * num18 * picu).toFixed(2));
    document.getElementById('<%=result17.ClientID%>').innerHTML = parseFloat((num1 * num19 * picu).toFixed(2));
    document.getElementById('<%=result18.ClientID%>').innerHTML = parseFloat((num1 * num20 * picu).toFixed(2));
    document.getElementById('<%=result20.ClientID%>').innerHTML = parseFloat((num1 * num22 * picu).toFixed(2));
    document.getElementById('<%=result21.ClientID%>').innerHTML = parseFloat((num1 * num23 * picu).toFixed(2));
    document.getElementById('<%=result22.ClientID%>').innerHTML = parseFloat((num1 * num24 * picu).toFixed(2));
    document.getElementById('<%=result19.ClientID%>').innerHTML = parseFloat((num1 * num21 * picu).toFixed(2));
    document.getElementById('<%=result23.ClientID%>').innerHTML = parseFloat((num1 * num25 * picu).toFixed(2));
    document.getElementById('<%=result24.ClientID%>').innerHTML = parseFloat((num1 * num26 * picu).toFixed(2));
    document.getElementById('<%=result25.ClientID%>').innerHTML = parseFloat((num1 * num27 * picu).toFixed(2));
    document.getElementById('<%=result26.ClientID%>').innerHTML = parseFloat((num1 * num28 * picu).toFixed(2));
    document.getElementById('<%=result27.ClientID%>').innerHTML = parseFloat((num1 * num29 * picu).toFixed(2));
    document.getElementById('<%=result28.ClientID%>').innerHTML = parseFloat((num1 * num30 * picu).toFixed(2));
    document.getElementById('<%=result29.ClientID%>').innerHTML = parseFloat((num1 * num31 * picu).toFixed(2));
    document.getElementById('<%=result30.ClientID%>').innerHTML = parseFloat((num1 * num32 * picu).toFixed(2));
    document.getElementById('<%=result31.ClientID%>').innerHTML = parseFloat((num1 * num33 * picu).toFixed(2));
    document.getElementById('<%=result32.ClientID%>').innerHTML = parseFloat((num1 * num34 * picu).toFixed(2));
    document.getElementById('<%=result33.ClientID%>').innerHTML = parseFloat((num1 * num35 * picu).toFixed(2));
    document.getElementById('<%=result34.ClientID%>').innerHTML = parseFloat((num1 * num36 * picu).toFixed(2));
    document.getElementById('<%=result35.ClientID%>').innerHTML = parseFloat((num1 * num37 * picu).toFixed(2));
    document.getElementById('<%=result36.ClientID%>').innerHTML = parseFloat((num1 * num38 * picu).toFixed(2));
    document.getElementById('<%=result37.ClientID%>').innerHTML = parseFloat((num1 * num39 * picu).toFixed(2));
    document.getElementById('<%=result38.ClientID%>').innerHTML = parseFloat((num1 * num40 * picu).toFixed(2));
    document.getElementById('<%=result39.ClientID%>').innerHTML = parseFloat((num1 * num41 * picu).toFixed(2));
    document.getElementById('<%=result40.ClientID%>').innerHTML = parseFloat((num1 * num42 * picu).toFixed(2));
    document.getElementById('<%=result41.ClientID%>').innerHTML = parseFloat((num1 * num43 * picu).toFixed(2));
    document.getElementById('<%=result42.ClientID%>').innerHTML = parseFloat((num1 * num44 * picu).toFixed(2));
    document.getElementById('<%=result43.ClientID%>').innerHTML = parseFloat((num1 * num45 * picu).toFixed(2));
    document.getElementById('<%=result44.ClientID%>').innerHTML = parseFloat((num1 * num46 * picu).toFixed(2));
    document.getElementById('<%=result45.ClientID%>').innerHTML = parseFloat((num1 * num47 * picu).toFixed(2));
    document.getElementById('<%=result46.ClientID%>').innerHTML = parseFloat((num1 * num48 * picu).toFixed(2));
    document.getElementById('<%=result47.ClientID%>').innerHTML = parseFloat((num1 * num49 * picu).toFixed(2));
    document.getElementById('<%=result48.ClientID%>').innerHTML = parseFloat((num1 * num50 * picu).toFixed(2));
    document.getElementById('<%=result49.ClientID%>').innerHTML = parseFloat((num1 * num51 * picu).toFixed(2));
    document.getElementById('<%=result50.ClientID%>').innerHTML = parseFloat((num1 * num52 * picu).toFixed(2));
    document.getElementById('<%=result51.ClientID%>').innerHTML = parseFloat((num1 * num53 * picu).toFixed(2));
    document.getElementById('<%=result52.ClientID%>').innerHTML = parseFloat((num1 * num54 * picu).toFixed(2));
    document.getElementById('<%=result53.ClientID%>').innerHTML = parseFloat((num1 * num55 * picu).toFixed(2));
    document.getElementById('<%=result54.ClientID%>').innerHTML = parseFloat((num1 * num56 * picu).toFixed(2));
    document.getElementById('<%=result55.ClientID%>').innerHTML = parseFloat((num1 * num57 * picu).toFixed(2));
    document.getElementById('<%=result56.ClientID%>').innerHTML = parseFloat((num1 * num58 * picu).toFixed(2));
    document.getElementById('<%=result57.ClientID%>').innerHTML = parseFloat((num1 * num59 * picu).toFixed(2));
    document.getElementById('<%=result58.ClientID%>').innerHTML = parseFloat((num1 * num60 * picu).toFixed(2));
    document.getElementById('<%=result59.ClientID%>').innerHTML = parseFloat((num1 * num61 * picu).toFixed(2));
    document.getElementById('<%=result60.ClientID%>').innerHTML = parseFloat((num1 * num62 * picu).toFixed(2));
    document.getElementById('<%=result61.ClientID%>').innerHTML = parseFloat((num1 * num63 * picu).toFixed(2));
    document.getElementById('<%=result62.ClientID%>').innerHTML = parseFloat((num1 * num64 * picu).toFixed(2));
    document.getElementById('<%=result63.ClientID%>').innerHTML = parseFloat((num1 * num65 * picu).toFixed(2));
    document.getElementById('<%=result64.ClientID%>').innerHTML = parseFloat((num1 * num66 * picu).toFixed(2));
    document.getElementById('<%=result65.ClientID%>').innerHTML = parseFloat((num1 * num67 * picu).toFixed(2));
    document.getElementById('<%=result66.ClientID%>').innerHTML = parseFloat((num1 * num68 * picu).toFixed(2));
    document.getElementById('<%=result67.ClientID%>').innerHTML = parseFloat((num1 * num69 * picu).toFixed(2));
    document.getElementById('<%=result68.ClientID%>').innerHTML = parseFloat((num1 * num70 * picu).toFixed(2));
    document.getElementById('<%=result69.ClientID%>').innerHTML = parseFloat((num1 * num71 * picu).toFixed(2));
    document.getElementById('<%=result70.ClientID%>').innerHTML = parseFloat((num1 * num72 * picu).toFixed(2));
    document.getElementById('<%=result71.ClientID%>').innerHTML = parseFloat((num1 * num73 * picu).toFixed(2));
    document.getElementById('<%=result72.ClientID%>').innerHTML = parseFloat((num1 * num74 * picu).toFixed(2));
    document.getElementById('<%=result73.ClientID%>').innerHTML = parseFloat((num1 * num75 * picu).toFixed(2));
    document.getElementById('<%=result74.ClientID%>').innerHTML = parseFloat((num1 * num76 * picu).toFixed(2));
    document.getElementById('<%=result75.ClientID%>').innerHTML = parseFloat((num1 * num77 * picu).toFixed(2));
    document.getElementById('<%=result76.ClientID%>').innerHTML = parseFloat((num1 * num78 * picu).toFixed(2));
    document.getElementById('<%=result77.ClientID%>').innerHTML = parseFloat((num1 * num79 * picu).toFixed(2));
    document.getElementById('<%=result78.ClientID%>').innerHTML = parseFloat((num1 * num80 * picu).toFixed(2));
    document.getElementById('<%=result79.ClientID%>').innerHTML = parseFloat((num1 * num81 * picu).toFixed(2));
    document.getElementById('<%=result80.ClientID%>').innerHTML = parseFloat((num1 * num82 * picu).toFixed(2));
    document.getElementById('<%=result81.ClientID%>').innerHTML = parseFloat((num1 * num83 * picu).toFixed(2));
    document.getElementById('<%=result82.ClientID%>').innerHTML = parseFloat((num1 * num84 * picu).toFixed(2));
    document.getElementById('<%=result83.ClientID%>').innerHTML = parseFloat((num1 * num85 * picu).toFixed(2));
    document.getElementById('<%=result84.ClientID%>').innerHTML = parseFloat((num1 * num86 * picu).toFixed(2));
    document.getElementById('<%=result85.ClientID%>').innerHTML = parseFloat((num1 * num87 * picu).toFixed(2));
    document.getElementById('<%=result86.ClientID%>').innerHTML = parseFloat((num1 * num88 * picu).toFixed(2));
    document.getElementById('<%=result87.ClientID%>').innerHTML = parseFloat((num1 * num89 * picu).toFixed(2));
    document.getElementById('<%=result88.ClientID%>').innerHTML = parseFloat((num1 * num90 * picu).toFixed(2));
    document.getElementById('<%=result89.ClientID%>').innerHTML = parseFloat((num1 * num91 * picu).toFixed(2));
    document.getElementById('<%=result90.ClientID%>').innerHTML = parseFloat((num1 * num92 * picu).toFixed(2));
    document.getElementById('<%=result91.ClientID%>').innerHTML = parseFloat((num1 * num93 * picu).toFixed(2));
    document.getElementById('<%=result92.ClientID%>').innerHTML = parseFloat((num1 * num94 * picu).toFixed(2));
    document.getElementById('<%=result93.ClientID%>').innerHTML = parseFloat((num1 * num95 * picu).toFixed(2));
    document.getElementById('<%=result94.ClientID%>').innerHTML = parseFloat((num1 * num96 * picu).toFixed(2));
    document.getElementById('<%=result95.ClientID%>').innerHTML = parseFloat((num1 * num97 * picu).toFixed(2));
    document.getElementById('<%=result96.ClientID%>').innerHTML = parseFloat((num1 * num98 * picu).toFixed(2));
    document.getElementById('<%=result97.ClientID%>').innerHTML = parseFloat((num1 * num99 * picu).toFixed(2));
    document.getElementById('<%=result98.ClientID%>').innerHTML = parseFloat((num1 * num100 * picu).toFixed(2));
    document.getElementById('<%=result99.ClientID%>').innerHTML = parseFloat((num1 * num101 * picu).toFixed(2));
    document.getElementById('<%=result100.ClientID%>').innerHTML = parseFloat((num1 * num102 * picu).toFixed(2));
    document.getElementById('<%=result101.ClientID%>').innerHTML = parseFloat((num1 * num103 * picu).toFixed(2));
    document.getElementById('<%=result102.ClientID%>').innerHTML = parseFloat((num1 * num104 * picu).toFixed(2));
    document.getElementById('<%=result103.ClientID%>').innerHTML = parseFloat((num1 * num105 * picu).toFixed(2));
    document.getElementById('<%=result104.ClientID%>').innerHTML = parseFloat((num1 * num106 * picu).toFixed(2));
    document.getElementById('<%=result105.ClientID%>').innerHTML = parseFloat((num1 * num107 * picu).toFixed(2));
    document.getElementById('<%=result106.ClientID%>').innerHTML = parseFloat((num1 * num108 * picu).toFixed(2));
    document.getElementById('<%=result107.ClientID%>').innerHTML = parseFloat((num1 * num109 * picu).toFixed(2));
    document.getElementById('<%=result108.ClientID%>').innerHTML = parseFloat((num1 * num110 * picu).toFixed(2));
    document.getElementById('<%=result109.ClientID%>').innerHTML = parseFloat((num1 * num111 * picu).toFixed(2));
    document.getElementById('<%=result110.ClientID%>').innerHTML = parseFloat((num1 * num112 * picu).toFixed(2));
    document.getElementById('<%=result111.ClientID%>').innerHTML = parseFloat((num1 * num113 * picu).toFixed(2));
    document.getElementById('<%=result112.ClientID%>').innerHTML = parseFloat((num1 * num114 * picu).toFixed(2));
    document.getElementById('<%=result113.ClientID%>').innerHTML = parseFloat((num1 * num115 * picu).toFixed(2));
    document.getElementById('<%=result114.ClientID%>').innerHTML = parseFloat((num1 * num116 * picu).toFixed(2));
    document.getElementById('<%=result115.ClientID%>').innerHTML = parseFloat((num1 * num117 * picu).toFixed(2));
    document.getElementById('<%=result116.ClientID%>').innerHTML = parseFloat((num1 * num118 * picu).toFixed(2));
    document.getElementById('<%=result117.ClientID%>').innerHTML = parseFloat((num1 * num119 * picu).toFixed(2));
    document.getElementById('<%=result118.ClientID%>').innerHTML = parseFloat((num1 * num120 * picu).toFixed(2));
    document.getElementById('<%=result119.ClientID%>').innerHTML = parseFloat((num1 * num121 * picu).toFixed(2));
    document.getElementById('<%=result120.ClientID%>').innerHTML = parseFloat((num1 * num122 * picu).toFixed(2));
    document.getElementById('<%=result121.ClientID%>').innerHTML = parseFloat((num1 * num123 * picu).toFixed(2));
    document.getElementById('<%=result122.ClientID%>').innerHTML = parseFloat((num1 * num124 * picu).toFixed(2));
    document.getElementById('<%=result123.ClientID%>').innerHTML = parseFloat((num1 * num125 * picu).toFixed(2));
    document.getElementById('<%=result124.ClientID%>').innerHTML = parseFloat((num1 * num126 * picu).toFixed(2));
    document.getElementById('<%=result125.ClientID%>').innerHTML = parseFloat((num1 * num127 * picu).toFixed(2));
    document.getElementById('<%=result126.ClientID%>').innerHTML = parseFloat((num1 * num128 * picu).toFixed(2));
    document.getElementById('<%=result127.ClientID%>').innerHTML = parseFloat((num1 * num129 * picu).toFixed(2));
    document.getElementById('<%=result128.ClientID%>').innerHTML = parseFloat((num1 * num130 * picu).toFixed(2));
    document.getElementById('<%=result129.ClientID%>').innerHTML = parseFloat((num1 * num131 * picu).toFixed(2));
    document.getElementById('<%=result130.ClientID%>').innerHTML = parseFloat((num1 * num132 * picu).toFixed(2));
    document.getElementById('<%=result131.ClientID%>').innerHTML = parseFloat((num1 * num133 * picu).toFixed(2));
    document.getElementById('<%=result132.ClientID%>').innerHTML = parseFloat((num1 * num134 * picu).toFixed(2));
    document.getElementById('<%=result133.ClientID%>').innerHTML = parseFloat((num1 * num135 * picu).toFixed(2));
    //);        
    //document.getElementByI'<%=d("result134").innerHTML = num1 * num112 * picu;
    //document.getElementByI'<%=d("result135").innerHTML = num1 * num112 * picu;
    //document.getElementByI'<%=d("result136").innerHTML = num1 * num112 * picu;
    //document.getElementByI'<%=d("result137").innerHTML = num1 * num112 * picu;
    //document.getElementByI'<%=d("result138").innerHTML = num1 * num112 * picu;
    //document.getElementByI'<%=d("result139").innerHTML = num1 * num112 * picu;
    //document.getElementByI'<%=d("result140").innerHTML = num1 * num112 * picu;
    //document.getElementByI'<%d("result141").innerHTML = num1 * num112 * picu;
    //document.getElementByI'<%d("result142").innerHTML = num1 * num112 * picu;
    //document.getElementByI'<%d("result143").innerHTML = num1 * num112 * picu;
    //document.getElementByI'<%d("result144").innerHTML = num1 * num112 * picu;
    //document.getElementByI'<%d("result145").innerHTML = num1 * num112 * picu;